### ISSUE TITLE
To-do list

### ISSUE THREAD

**Issue by Mr-Smarty** [Mr-Smarty/BTE-Theme-Parks-BOT#1]
- [x] change bot icon
- [x] remove wvg reaction
- [x] send server bot id and token to adam
- [ ] server commands

**Comment by HakkaTjakka** [comment]
I've made Holland (The Netherlands) and putted it online on GitHub.
Maybe you can report it so i will get banned here to.

https://github.com/HakkaTjakka/sample-utrecht

Good luck with your 'terms of service'. 
Obey like a sick little puppy to a multi multi billion company that steals and scannes all peoples data for commercial purposes.
Did they put my property in streetview and google earth 3d with MY CONSENT, WITH MY TERMS OF SERVICE?
I've never agreed to Google putting my property online.
Obey! Obey! Obey! Obey! Obey! Obey! Obey! To the big companies.

**Comment by HakkaTjakka** [comment]
Take a look at the whole of The Netherlands. First country complete (MOLD!) in BTE121 projection.

http://83.83.222.154/nl/
